{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "osdf-origin.fullname" . }}
  labels:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ template "osdf-origin.fullname" . }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ .Values.topologyFQDN | quote }}
    {{- with .Values.serviceAnnotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if or (eq .Values.service.type "LoadBalancer") (eq .Values.service.type "NodePort") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    {{- if .Values.publicOrigin.enabled }}
    - port: {{ default 1094 .Values.publicOrigin.port }}
      targetPort: 1094
      protocol: TCP
      name: xrootd-stash-origin
    {{- end }}
    {{- if .Values.authOrigin.enabled }}
    - port: {{ default 1095 .Values.authOrigin.port }}
      targetPort: 1095
      protocol: TCP
      name: xrootd-stash-origin-auth
    {{- end }}
    {{- if .Values.monitoringShoveler.enabled }}
    - name: shoveler
      protocol: UDP
      port: 9993
      targetPort: shoveler
    - name: stats
      protocol: TCP
      port: 9667
      targetPort: stats
    {{- end }}
  selector:
    app: {{ template "osdf-origin.name" . }}
    release: {{ .Release.Name }}
    instance: {{ template "osdf-origin.fullname" . }}
{{- end }}
